### ISSUE TITLE
里程碑/Milestone v1.0.0

### ISSUE THREAD

**Issue by danranVm** [IDuxFE/idux#2]
# Milestone: [@idux v1.0.0](https://github.com/IduxFE/components/milestone/1)

## 脚本

- [x] gen: 创建组件模板 @danranVm #3 
- [x] ci: lint, test, preview @danranVm #8 #10 #216 #218 
- [x] build #276 #277

## 文档

- [x] Markdown 解析 @danranVm #13
- [x] Website @danranVm #41 #166 #181
- [ ] 样式优化
- [x] 在线 Demo @jeasonzone #348 
- [ ] 多语言

## 工具

- [x] PR Bot @danranVm #216
- [x] Issue Templates @danranVm #19

## Less

- [x] 基础变量 @danranVm #37 
- [x] 默认主题

## CDK

- [x] breakpoint @danranVm #44 
- [x] click outside @LaamGinghong #207 
- [x] clipboard @danranVm #14 
- [ ] drag/drop
- [x] forms @danranVm #114 #153 
- [x] overlay @LaamGinghong #113
- [x] platform @danranVm #44
- [x] portal @LaamGinghong #113
- [] resize @danranVm #909 
- [x] subject @LaamGinghong #154 
- [x] utils @clfeng @danranVm 
- [x] virtual-list @danranVm #325 

## Componnets

- [x] General 通用
  - [x] Button 按钮 @danranVm #11 
  - [x] Icon 图标 @danranVm #20 
  - [x] Title 标题 @danranVm #188
  - [x] Typography 排版 @LaamGinghong #130
- [x] Layout 布局
  - [x] Layout 布局 @liuzaijiang #425
  - [x] Grid 栅格@zymoplastic #133
  - [x] Divider  分割线 @LaamGinghong #32 
  - [x] Space 间距 @LaamGinghong #63
- [x] Navigation 导航
  - [x] Affix 固钉 @jackson-yyy #138
  - [x] Breadcrumb 面包屑 @mrliusu #71
  - [x] Dropdown 下拉菜单 @danranVm #311 
  - [x] Menu 导航菜单 @danranVm #229
  - [x] Pagination 分页 @zymoplastic #98
  - [x] Steps 步骤条 @ShannyShanny #91
  - [ ] ~~PageHeader 页头 @qingshan-dev #228~~

- [ ] Data Entry 数据录入
  - [x] Checkbox 多选框 @liuzaijiang #120 
  - [x] DatePicker 日期选择框 #541 @danranVm 
  - [x] Form 表单 @danranVm #27 
  - [x] Input 输入框 @danranVm #158 
  - [x] Radio 单选框 @lwh2015 #92 
  - [x] Select 选择器 @danranVm #212 
  - [x] TreeSelect 树选择 #557 @liuzaijiang 
  - [x] ~~AutoComplete 自动完成 #680~~
  - [x] Cascader 级联选择 @danranVm #797 
  - [x] Switch 开关 @jiayinkong #75
  - [x] TimePicker 时间选择框 @jackson-yyy #222
  - [x] Transfer 穿梭框 @sallerli1 #782 
  - [x] Upload 上传 @typistZxd #605 
  - [x] InputNumber 数字输入框 @calvinchan22 #31 
  - [ ] Mentions 提及 @lionnnnn #359
  - [x] Rate 评分 @CocaColf #34 
  - [x] Slider 滑动输入条 @imguolao #186
- [ ] Data Display 数据展示
  - [x] Badge 徽标数 @KnorienChang #64
  - [x] Collapse 折叠面板 @Usualminds #70
  - [x] Card 卡片 @CruellyJoHn #28 
  - [x] Empty 空状态 @qikong333 #54
  - [x] Image 图片 @lwh2015 #30 
  - [x] List 列表 @rhinonan #187 
  - [x] Popover 气泡卡片 @LaamGinghong #193 
  - [x] Tree 树形控件 @danranVm #446
  - [x] Tooltip 文字提示 @LaamGinghong #200
  - [x] Tag 标签 @Gilbert5210 #29
  - [x] Tabs 标签页 @LaamGinghong #195 
  - [x] Table 表格 @danranVm #394 
  - [x] Avatar 头像 @danranVm #55
  - [x] Carousel 走马灯 @thinkingOfBetty #230 
  - [ ] Descriptions 描述列表
  - [x] Timeline 时间轴 @sjia0307 #69 
  - [x] Comment 评论 @lionnnnn #358 
  - [ ] Calendar 日历
  - [x] Statistic 统计数值 @clfeng #95
- [x] Feedback 反馈
  - [x] Alert 警告提示 @brenner8023 #43 #520 
  - [x] Drawer 抽屉 @huiyimeijiaodian #227
  - [x] Modal 对话框 @danranVm #346 
  - [x] Message 全局提示 @manchixue #36
  - [x] Popconfirm 气泡确认框 #555 @ttdegit 
  - [x] Spin 加载中 @liuzaijiang #72
  - [x] Notification 通知提醒框 #545 @lo56ve 
  - [x] Progress 进度条 @hangboss1761 #35
  - [x] Skeleton 骨架屏 @Pupils-web #94 
  - [x] Result 结果 @LaamGinghong #112 
- [x] Other 其他
  - [x] core 全局化配置 @danranVm #5 
  - [x] I18n 国际化 @danranVm #59 
  - [x] BackTop 回到顶部 @imguolao #79
  - [x] Anchor 锚点 @bunnybunny3 #93

**Comment by danranVm** [comment]
# Check List

- [ ] cdk
  - [ ] a11y 
    - [ ] API
    - [ ] 文档
    - [ ] 单测
  - [ ] breakpoint 
    - [ ] API
    - [ ] 文档
    - [ ] 单测
  - [ ] click-outside 
    - [ ] API
    - [ ] 文档
    - [ ] 单测
  - [ ] clipboard 
    - [ ] API
    - [ ] 文档
    - [ ] 单测
  - [ ] forms 
    - [ ] API
    - [ ] 文档
    - [ ] 单测
  - [ ] platform 
    - [ ] API
    - [ ] 文档
    - [ ] 单测
  - [ ] popper 
    - [ ] API
    - [ ] 文档
    - [ ] 单测
  - [ ] portal 
    - [ ] API
    - [ ] 文档
    - [ ] 单测
  - [ ] scroll 
    - [ ] API
    - [ ] 文档
    - [ ] 单测
  - [ ] utils 
    - [ ] API
    - [ ] 文档
    - [ ] 单测
- [ ] components
  - [ ] affix
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] alert
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] anchor
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] avatar
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] back-top
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] badge
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] button
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] card
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] checkbox
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] collapse
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] date-picker
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] divider
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] drawer
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] dropdown
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] empty
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] form
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] grid
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] header
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] icon
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] image
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] input
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] input-number
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] layout
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] list
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] menu
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] message
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] modal
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] notification
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] pagination
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] popconfirm
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] popover
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] progress
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] radio
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] rate
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] result
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] select
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] skeleton
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] slider
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] space
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] spin
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] statistic
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] stepper
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] switch
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] table
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] tabs
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] tag
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] textarea
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] time-picker
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] timeline
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] tooltip
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] tree
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] typography
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
  - [ ] utils
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
- [ ] pro
  - [ ] layout
    - [ ] API
    - [ ] 视觉检视
    - [ ] 文档
    - [ ] 单测
- [ ] other
  - [ ] config
    - [ ] API
    - [ ] 文档
    - [ ] 单测
  - [ ] i18n
    - [ ] API
    - [ ] 文档
    - [ ] 单测
  - [ ] changelog
    - [ ] 脚本
    - [ ] 文档
  - [ ] themes
    - [ ] 方案
    - [ ] 文档

**Comment by huiyimeijiaodian** [comment]
陈嘉兴已收到您的来信！谢谢
